require:
  - rubocop-rails

LineLength:
  Max: 130

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'
